---
cidr_networks:
  container: 172.29.236.0/22
  tunnel: 172.29.240.0/22
  storage: 172.29.244.0/22

used_ips:
  - "172.29.236.1,172.29.236.100"
  - 172.29.236.107
  - "172.29.240.1,172.29.240.100"
  - "172.29.244.1,172.29.244.100"

global_overrides:
  internal_lb_vip_address: 172.29.236.11 # TODO: burasi duzgun ayarlanmali
  external_lb_vip_address: 10.1.37.31 
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"

  provider_networks:    
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"  # TODO: burasi duzgun ayarlanmali
        ip_from_q: "container"
        type: "vxlan"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true    
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"  # TODO: burasi duzgun ayarlanmali
        ip_from_q: "storage"
        type: "raw" # TODO: burasi duzgun ayarlanmali
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"  # TODO: burasi duzgun ayarlanmali
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "em2"    #TODO: burasi duzgun ayarlanmali
        type: "flat"
        net_name: "flat"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1000"
        net_name: "vlan"

shared-infra_hosts:
  ansible01:
    ip: 172.29.236.11
  ansible02:
    ip: 172.29.236.12
  ansible03:
    ip: 172.29.236.13

repo-infra_hosts:
  ansible01:
    ip: 172.29.236.11
  ansible02:
    ip: 172.29.236.12
  ansible03:
    ip: 172.29.236.13

os-infra_hosts:
  ansible01:
    ip: 172.29.236.11
  ansible02:
    ip: 172.29.236.12
  ansible03:
    ip: 172.29.236.13

identity_hosts:
  ansible01:
    ip: 172.29.236.11
  ansible02:
    ip: 172.29.236.12
  ansible03:
    ip: 172.29.236.13

network_hosts:
  ansible01:
    ip: 172.29.236.11
  ansible02:
    ip: 172.29.236.12
  ansible03:
    ip: 172.29.236.13

compute_hosts:
  ansible05:
    ip: 172.29.236.15

storage-infra_hosts:
  ansible01:
    ip: 172.29.236.11
  ansible02:
    ip: 172.29.236.12
  ansible03:
    ip: 172.29.236.13

storage_hosts:
  ansible06:
    ip: 172.29.236.16
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "172.29.236.16" # TODO: storage address diye geciyor dokumanda

log_hosts:
  ansible04:
    ip: 172.29.236.14

haproxy_hosts:
  b3lab_haproxy:
    ip: 172.29.236.11

